### ISSUE TITLE
Button To Add A Cluster

### ISSUE THREAD

**Issue by DannyeB** [razee-io/Razeedash#202]
**Is your feature request related to a problem? Please describe.**
After setting up Razee on my first cluster on the dashboard I have no way to add a new cluster. I need to logout and back in to get to the org selection screen. From there I need to go to manage and get the `Install Razee Agent` command. Why is it so awkward to get to?

**Describe the solution you'd like**
When on the clusters screen I expect there to be an add cluster button. This could either bring you to the manage org screen or bring up a dialog box with the `Install Razee Agent` command.

**Describe alternatives you've considered**

**Additional context**

**Comment by mckaymic** [comment]
@DannyeB .  Sorry this got closed.  You bring up a good point that the URL to add new clusters is buried in a weird place.  We'll look to see what we can do to improve this (probably putting a button on the clusters page).  Any suggestions would be appreciated.

**Comment by mckaymic** [comment]
@DannyeB .  Hi.  We added a link to the top of the pages which gives the user easy access to the "Add cluster" link now.  In addition there is a quick link to the org management page.  Hopefully this works out for you.
![image](https://user-images.githubusercontent.com/5192250/76449498-92fb0e80-63a2-11ea-9b5f-2cb01a83dfbe.png)

**Comment by DannyeB** [comment]
Looks good! Thank's for this
