### ISSUE TITLE
Cluster refresh button

### ISSUE THREAD

**Issue by alewitt2** [razee-io/Razeedash#65]
**Describe the solution you'd like**
Add a toggle switch on the cluster view that will kick off a polling cycle in watch-keeper. This means the next time watch-keeper sends the heartbeat post, it will get a 205 response which will tell it to re-poll and send the data to razeedash. the toggle should be switched off once the polled data is received or if the user no longer wants it toggled. 

**Additional context**
Here is the spot where watch-keeper uses to know whether to poll based on refresh https://github.com/razee-io/Watch-keeper/blob/master/src/razeedash/Heartbeat.js#L64-L65
and here is where it does the polling if refresh is true https://github.com/razee-io/Watch-keeper/blob/master/src/index.js#L57-L61

**Comment by rmgraham** [comment]
Fixed by https://github.com/razee-io/Razeedash/pull/82
