### ISSUE TITLE
Cluster count in masthead doesn't match cluster listing view

### ISSUE THREAD

**Issue by jpapejr** [razee-io/Razeedash#76]
**Describe the bug**
After adding the the forth cluster to my Razee deployment, the `Clusters` counter/badge in the masthead still shows 3 and not four. Yet, clicking on the `Clusters` link correctly displays the four clusters.

**To Reproduce**
1. Browse to the org and click manage
2. Get install command string and run on new cluster target
3. After new cluster has started reporting in razee, note the cluster count at the top of the page doesn't match the actual count of clusters

**Expected behavior**
Cluster view count should match the value in the masthead (which seems to come from the `resourceStats` collection in the `RazeeDash` db in mongodb.

**Screenshots**
<img width="842" alt="Screen Shot 2019-06-07 at 9 06 08 AM" src="https://user-images.githubusercontent.com/213203/59106303-16636d00-8904-11e9-8a06-0b98330d3d83.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Browser Safari
 - Version 12.1.1

**Smartphone (please complete the following information):**
n/a

**Additional context**
None

**Comment by jpapejr** [comment]
FWIW - my latest cluster added is an OpenShift (beta on IBM Cloud) cluster..

**Comment by dalehille** [comment]
@jpapejr we pushed a new version of razeedash yesterday which should have fixed the problem.  Are you still seeing this issue?

**Comment by jpapejr** [comment]
Nope, looks fine now. I'll report if I see anything contrary. Thanks!
